# This file is installed into /etc/nginx/conf.d, which is loaded in the http context.
limit_conn_zone $binary_remote_addr zone=perip:10m;
limit_req_zone $binary_remote_addr zone=api_perip:10m rate=30r/s;
